
project: my-project

# Set this if you want to carry over parent process' environment variables
# carry_env: true 


#
# Variables
#
# Feel free to add options here to be used as a variable throughout
# paths.
#
opts:
  region: env:AWS_REGION    # you can get env variables with the 'env:' prefix
  stage: development


#
# Providers
#
providers:
  # configure only from environment
  aws_secretsmanager:
    env:
      ADMIN_USER:
        path: dev/test/admin
        field: user
      SECRET:
        path: dev/test/admin
        field: secret
  github:
    env_sync:
      path: b-nova-techup/teller-golang
